configurations {
	twitchLibraries {
		canBeResolved = true
		canBeConsumed = false
		exclude group: 'org.slf4j', module: 'slf4j-api'
		exclude group: 'commons-io', module: 'commons-io'
		exclude group: 'org.apache.commons', module: 'commons-lang3'
	}
}

clientGameTestRecorder {
	runDir.set(layout.buildDirectory.dir('run/productionClientGameTest'))
	guiScale.set('3')
}


dependencies {
	twitchLibraries "com.github.twitch4j:twitch4j:${rootProject.twitch4j_version}"
	implementation files(configurations.twitchLibraries)
	configurations.twitchLibraries.resolvedConfiguration.resolvedArtifacts.each { artifact ->
		include("${artifact.moduleVersion.id.group}:${artifact.name}:${artifact.moduleVersion.id.version}") {
			transitive = false
		}
	}
}
productionGameTests {
	runtimeLibraryDependencies.set(configurations.twitchLibraries.resolvedConfiguration.resolvedArtifacts.collect {
		"${it.moduleVersion.id.group}:${it.name}:${it.moduleVersion.id.version}"
	})
}
