plugins {
	id 'io.github.brainage04.fabric-mod-conventions' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.workspace-dependencies' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.mod-publishing' version "${fabricmoddingconventions_version}"
}

repositories {
	mavenCentral()
}

workspaceDependencies {
	siblingMaven("FabricModdingConventions") {
		coordinate.set("io.github.brainage04:fabricmoddingconventions:${project.fabricmoddingconventions_version}")
	}
}

configurations {
	twitchLibraries {
		canBeResolved = true
		canBeConsumed = false
		exclude group: 'org.slf4j', module: 'slf4j-api'
		exclude group: 'commons-io', module: 'commons-io'
		exclude group: 'org.apache.commons', module: 'commons-lang3'
	}
}


dependencies {
	twitchLibraries "com.github.twitch4j:twitch4j:${project.twitch4j_version}"
	implementation files(configurations.twitchLibraries)
	configurations.twitchLibraries.resolvedConfiguration.resolvedArtifacts.each { artifact ->
		include("${artifact.moduleVersion.id.group}:${artifact.name}:${artifact.moduleVersion.id.version}") {
			transitive = false
		}
	}
}
