configurations {
	twitchLibraries {
		canBeResolved = true
		canBeConsumed = false
		exclude group: 'org.slf4j', module: 'slf4j-api'
		exclude group: 'commons-io', module: 'commons-io'
		exclude group: 'org.apache.commons', module: 'commons-lang3'
	}
}

dependencies {
	compileOnly files(configurations.twitchLibraries)
	twitchLibraries "com.github.twitch4j:twitch4j:${rootProject.twitch4j_version}"
	testImplementation platform('org.junit:junit-bom:6.0.3')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test { useJUnitPlatform() }
