name: build

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: brainage04/FabricModdingConventions/.github/workflows/reusable-mod-build.yml@v2.3.8
